### Teste
GET http://localhost:5062/olamundo

### Cadastrar um produto
POST http://localhost:5062/api/produto/cadastrar
Content-Type: application/json

{
    "nome" : "Fone de ouvido",
    "descricao" : "Texto exemplo"
}

### Listar todos os produtos
GET http://localhost:5062/api/produto/listar

### Listar um produto especifico buscando pelo id
GET http://localhost:5062/api/produto/buscar/3

### Deletar um produto buscando pelo id
DELETE http://localhost:5062/api/produto/deletar/3

### Alterar um produto pelo id
PUT http://localhost:5062/api/produto/alterar/2
Content-Type: application/json

{
    "nome" : "Iphone",
    "descricao" : "Texto exemplo 2"
}